### ISSUE TITLE
Run literate-programming from script

### ISSUE THREAD

**Issue by zimt28** [jostylr/literate-programming#12]
Is there a way I can use the library from a script? I'd like to use it with Meteor.js and I'd need to run the command from node :)

**Comment by jostylr** [comment]
The core library has been updated and now does not depend on the command line. One has to plugin what save and load do, but other than that, it works. You can find it at 
[litpro lib](https://github.com/jostylr/literate-programming-lib).  Very soon, I will write a command line client to go with it and then develop plugins for it, eventually updating this to rely on it all. 

There are some syntax changes. In particular, reduced syntax with increased power. A lot more async stuff going on.
