### ISSUE TITLE
Single period after a named code block causes error

### ISSUE THREAD

**Issue by Wideshanks** [jostylr/literate-programming#14]
If I use a single period on the next line after a named code block, like so:

``` markdown
`$255` ←
[address of program name]()
.
```
See context at https://github.com/Wideshanks/mmix-hw/commit/ea56c340dd9a1e227ba99f0daec7e10f37c8957c

I get build errors:
![image](https://cloud.githubusercontent.com/assets/2061925/5912929/e318ae9e-a5a8-11e4-8e49-f4b0f0870b07.png)

Any other word, or single character like a letter, comma, dash, or more than one period works successfully.

**Comment by jostylr** [comment]
Fixed. It was a deprecated feature. In the old days, the switch parsers were a ". SWITCH NAME". It was deprecated awhile ago and forgotten, but I have now removed it. Tests pass and this problem is removed. Check out v 0.8.3
