### ISSUE TITLE
Some kind of regex-bug ... not compiling js-block on using double-quotes in special circumstances

### ISSUE THREAD

**Issue by joehannes** [jostylr/literate-programming#16]
[error.js](#CompileError "save:")

## CompileError

I don't understand what's wrong with this, I just guess some regex is failing
To see and disbelief with a mouth wide open please copy and paste this into a *.md file and try to literate-programming-process it.
Then, to really freak out ... replace the double quotes with single-quotes ... et voila, it works ...?!??

```javascript
    if (typeof fn !== "function" ||
        key === "constructor" ||
        key[0] === "_" ||
        key.match("::")) {
```

**Comment by jostylr** [comment]
The problem is that `_"`  starts a block substitution. So you read it as `"_"` but the part looking for a substitution sees `_"`

One fix is to use the unicode for underscore, i.e.,  `"\u005F"` 

The new version has backslash escaping.
