### ISSUE TITLE
Trying to load non existent block  during save

### ISSUE THREAD

**Issue by cjloong** [jostylr/literate-programming#17]
I have a block
<pre>
- [engineering2.html](#html "Save:")

# Html
```
test code
```
</pre>

The above code will give "Trying to load non existent block 'html'" on a windows 8 platform.

**Comment by jostylr** [comment]
That should work. I copied that block and put it in a new file. It compiled and worked just fine. This worked fine for version 0.8.4 

I am on a Mac, but I don't see why the operating system would be a problem for this error.

You can also try the newer version being developed:  https://github.com/jostylr/litpro  is the minimal client version. Eventually, a batteries-included version will be what literate-programming will become.

Does the snippet above in its own file give you a problem? If there is more in the file, can you paste the whole file?

**Comment by cjloong** [comment]
This is the whole file
<pre>
# Overview

- [engineering2.html](#html "Save:")

# Html
```
test code
```
</pre>

This is the output
<pre>
C:\Users\chekjen\AppData\Roaming\npm\node_modules\literate-programming\lib\literate-programming.js:1004
      fp.codeblock = hcur.cblocks[hcur.cname].lines;
                                             ^
TypeError: Cannot read property 'lines' of undefined
    at Array.Doc.defaultProcessors.hcur (C:\Users\chekjen\AppData\Roaming\npm\node_modules\literate-programm
rate-programming.js:1004:46)
    at Doc.parseLines (C:\Users\chekjen\AppData\Roaming\npm\node_modules\literate-programming\lib\literate-p
s:1309:29)
    at new Doc (C:\Users\chekjen\AppData\Roaming\npm\node_modules\literate-programming\lib\literate-programm
)
    at Object.<anonymous> (C:\Users\chekjen\AppData\Roaming\npm\node_modules\literate-programming\bin\litera
ng.js:185:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

C:\Users\chekjen\git\evo\public\evo\csp\test>
</pre>


When I don't use hash as header it works
<pre>
# Overview

- [engineering2.html](#html "Save:")

Html
----
```
test code
```

</pre>
<pre>
C:\Users\chekjen\git\evo\public\evo\csp\test>literate-programming test2.md
File engineering2.html saved

C:\Users\chekjen\git\evo\public\evo\csp\test>
</pre>

**Comment by jostylr** [comment]
Not sure what to do. That file continues to work for me. I tried different versions of node, just in case. All worked fine. Unfortunately, I don't have a windows 8 machine to try.

I don't know why changing to the underline would work but the hash does not. Maybe there is some kind of space or strange invisible character? I'll ponder it, but can you try litpro on it?

**Comment by cjloong** [comment]
Ok, I'll try litpro tonight. Thanks.

**Comment by cjloong** [comment]
Looks like it works in litpro.

**Comment by jostylr** [comment]
That's good to know. Hopefully I can get litpro to be the main one in a couple of weeks.
