### ISSUE TITLE
Inline code blocks?

### ISSUE THREAD

**Issue by yrashk** [jostylr/literate-programming#18]
First of all, thanks for literate-programming, I think it's fun!

I've got a question. Is there a way to use inline code blocks, something like the one below?

```markdown
This value has a [version](#)`0.1.0` in it.
```

So far it seems like this won't generate a 'version' block within the section it is in. Thoughts?

P.S. I am working on this: https://github.com/reactuate/reactuate and it feels like version definitions are a little bulky.

**Comment by jostylr** [comment]
Inline-code blocks do not do anything, but your version is close to what one can do with the new version of this tool whose barebones version is litpro:  https://www.npmjs.com/package/litpro 

In litpro,  you can do  `[name](# "store:value |...")` where the name is the variable name and the value is the value to be stored. Now that I look at it, I might want to change it so the value is part of the link name, say  `[name|value]`

But for your use case, I have a setup that might be more useful. If you look at https://raw.githubusercontent.com/jostylr/litpro/master/project.md  you can see at the top the version directive and at the bottom the npminfo directive. 

You can learn the most about the new version at https://github.com/jostylr/literate-programming-lib 

Litpro is much more powerful than the old version, but it should largely work with the older files. Eventually I will update literate-programming to be a full-battery version of litpro, once I update examples and create a migration guide.
